# Generated by Django 3.0.3 on 2020-03-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbres_Remarquables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_français', models.CharField(max_length=60)),
                ('famille', models.CharField(max_length=60)),
                ('parcours', models.CharField(max_length=60)),
                ('num_parcours', models.IntegerField()),
            ],
        ),
    ]
