# Generated by Django 3.0.3 on 2020-03-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbres_remarquables',
            name='nom_scientifique',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='arbres_remarquables',
            name='famille',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='arbres_remarquables',
            name='nom_français',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
